### ISSUE TITLE
HSBC Premier - ordem de pagamento

### ISSUE THREAD

**Issue by joaocunha** [DyegoCosta/trabalhando-remoto#10]
Passei no HSBC hoje e a taxa de conversão no Premier para ordem de pagamento está em 2,99 - bastante abaixo dos 3,14 de hoje.

Dá pra fazer o fechamento por telefone ligando para a gerente e é gratuito, mas tem um certo limite de valores. Também fazem fechamento fisicamente com assinatura, onde o limite é mais alto, mas cobram uma taxa de R$30,00. De qualquer forma, o Premier manda alguém na sua casa para colher a assinatura.

**Comment by DyegoCosta** [comment]
@joaocunha você sabe dizer qual é esse limite para que a transação possa ser feita sem custo pelo telefone? E essa assinatura é necessária para todos os fechamentos, inclusive os feitos por telefone?

**Comment by joaocunha** [comment]
@DyegoCosta vou conversar novamente com a gerente porque não tive muito tempo, aí atualizo a issue.

**Comment by DyegoCosta** [comment]
@joaocunha Vou commitar as informações que você passou e depois atualizamos com as novas informações que você conseguir. Após atualizarmos fechamos esse issue

**Comment by DyegoCosta** [comment]
@joaocunha chegou a conversar com a gerente?

**Comment by DyegoCosta** [comment]
Qualquer novidade pode abrir outro issue ou um PR. Valeu!

**Comment by joaocunha** [comment]
Ainda não, @DyegoCosta... assim que tiver novidades eu atualizo a issue.
