### ISSUE TITLE
Contrato de prestação de serviço - assinatura digital ou manual suficiente?

### ISSUE THREAD

**Issue by praguc** [DyegoCosta/trabalhando-remoto#113]
Olá galera, 

Alguém já recebeu dinheiro como PF no montante maior de $3000.. Vi que precisa ter um contrato, agora o que não sei é se precisa assinatura digital o é suficiente uma assinatura de mão? Eu vou ter o contrato, mas não tenho assinatura digital. Sou pessoa física.

Alguém já passou por isso?

**Comment by raulfragoso** [comment]
Já precisei enviar algumas vezes o contrato de prestação de serviços, inclusive como pessoa física, em todas as vezes enviei o contrato com a assinatura feita à mão e digitalizada, ou seja, escaneei a minha assinatura, pedi ao diretor da empresa contratante para que fizesse o mesmo, daí removi o fundo e deixei como um arquivo PNG, inseri as assinaturas no contrato feito no Word, exportei como PDF e enviei ao banco. Já fiz assim com o Itaú e o Inter (pessoa física) e na última vez foi o Rendimento para usar com Payoneer para receber como PJ, nunca tive problemas.

**Comment by praguc** [comment]
Ótimo Raul, muito obrigado pelas informações.
