### ISSUE TITLE
Reembolso para empresas no Simples

### ISSUE THREAD

**Issue by lucas-barros** [DyegoCosta/trabalhando-remoto#116]
Trabalho para uma empresa americana e eles vão me pagar um notebook para o trabalho. Queria saber como receber esse valor sem que isso entre para o faturamento, visto que é um reembolso. Também não consegui usar o cartão de credito deles, no site da apple não consigo colocar endereço de cobrança de outro pais. 
Meu contrato com eles é com minha empresa que está no Simples. 

Alguém já passou por isso?

**Comment by samiraguiar** [comment]
Não dá pra eles comprarem de lá e mandarem entregar aí? Outra ideia seria comprar pela Amazon, que é mais flexível quanto a isso do cartão.
Eu tentaria uma forma de eles comprarem de lá, porque dei uma pesquisada e parece ser bem chatinha essa questão de reembolso.[[1]](https://www.ozai.com.br/os-reembolsos-de-despesas-devem-ser-tributados/)[[2]](http://www.contabilcarlos.com.br/boletim/reembolso-de-despesas-tributacao-216)

**Comment by shamanime** [comment]
No meu contrato havia uma cláusula de reembolso pra poder eventualmente receber mais do que o valor do serviço. No meu caso eu cobrava da empresa o valor que paguei e o valor extra do imposto sobre o "faturamento". É chato mas eles eram compreensivos e cobriam o imposto pra eu não sair no prejuízo.

**Comment by copercini** [comment]
Acho que não tem muito o que fazer, pois entra como faturamento e infelizmente tem que pagar os impostos sobre o valor
Mas como o @samiraguiar um dos caminhos é vc comprar no Amazon US com o cartão da empresa e mandar entregar aqui, a Amazon já inclui os impostos de importação durante a compra, então já chega certinho para você

**Comment by samiraguiar** [comment]
@copercini dá pra eles comprarem na Amazon BR também (acho que vai sair mais barato que importar). Um tempo atrás uma amiga que mora nos EUA me comprou um presente direto pela Amazon BR e foi tudo certo.
Como é multinacional, deve ser bem tranquilo pra eles declareram isso como despesa da empresa pro fisco de lá.

**Comment by lucas-barros** [comment]
Obrigado pelas sugestões! Pela Amazon BR não achei nenhum mac, acho que vai ser por transferência mesmo.
