### ISSUE TITLE
Seção de conselhos e depoimentos

### ISSUE THREAD

**Issue by vanessametonini** [DyegoCosta/trabalhando-remoto#15]
O que acha de fazermos uma seção de conselhos ou depoimentos de quem faz home-office?

**Comment by joaocunha** [comment]
:+1:.

Talvez um wiki funcione bem para isso.

**Comment by vanessametonini** [comment]
Hum, na verdade todo o conteúdo desse repositório ficaria melhor numa wiki...
Vocês tem a intenção de tornar-lo em um page?

**Comment by DyegoCosta** [comment]
Ótima ideia @vanessametonini! E concordo com o @joaocunha, uma wiki page fica mais fácil para o pessoa contribuir.

Vamos criar uma wiki e colocar o link para ela no README. Acho que inicialmente pode ser uma só chamada `Conselhos de Depoimentos` e caso ela fique muito grande podemos dividir em duas.

Eu vou poder fazer isso daqui umas horas, mas ainda hoje posso postar. Se algum de vocês quiser pode criar e mandar um PR com o link no README.

Podemos ir experimentando formatos diferentes mas acho que para cada conselho/depoimento podemos usar os [Blockquotes](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes) do Markdown e linkar o autor ao seu github ou outra rede social.

**Comment by DyegoCosta** [comment]
@vanessametonini por enquanto ficaremos com o README, na minha opinião é bem prático e com informações bem minimalistas e objetivas. Qualquer conteúdo que seja mais extenso acredito que possa se tornar uma wiki, como por exemplo o arquivo `bancos.md` que eu criei recentemente, agor aque você comentou acredito que ele possa ser uma wiki.
Mas o conteúdo principal eu ainda sou a favor de mantê-lo no formato atual

**Comment by vanessametonini** [comment]
@DyegoCosta uhum podemos fazer isso que vc comentou primeiro :)

> Podemos ir experimentando formatos diferentes mas acho que para cada conselho/depoimento podemos usar os Blockquotes do Markdown e linkar o autor ao seu github ou outra rede social.

**Comment by DyegoCosta** [comment]
@vanessametonini @joaocunha o único detalhe é que precisamos iniciar a page com algum conteúdo :grimacing:
Acho que hoje não consigo escrever um depoimento mas em breve posso contribuir com isso. Mas se algum de vocês ou alguém que estiver lendo quiser iniciar a page com algum conteúdo próprio eu super apoio!

**Comment by joaocunha** [comment]
@DyegoCosta @vanessametonini façamos assim: adicionamos uma nota no `readme.md` pedindo PRs com depoimentos em formato `.md`. Conforme forem chegando, podemos organizar e distribuir.

**Comment by DyegoCosta** [comment]
@joaocunha @vanessametonini vou adicionar essa nota e ficamos no aguardo. Assim que possível contribuirei com meu depoimento

**Comment by vanessametonini** [comment]
Show!! Vou ver se consigo um tempinho pra ajudar nisso hoje também :smile:

**Comment by cassiosvaldo** [comment]
@DyegoCosta  @vanessametonini  os conselhos estão no readme? caí de paraquedas aqui e achei bacana a iniciativa de vocês. Vou ficar acompanhando.

**Comment by DyegoCosta** [comment]
@cassiosvaldo no README tem uma chamada para as pessoas que quiserem fazer algum depoimento. Por enquanto não temos nenhum mas assim que houver algum será criada uma wiki page e o link estará disponível no README
