### ISSUE TITLE
Cupons Husky/outros cupons: A Thread

### ISSUE THREAD

**Issue by Joaovtrc** [DyegoCosta/trabalhando-remoto#153]
Vi o @lmanerich falando pra criar uma issue somente pra cupons do Husky.

Estou na busca de um, se alguém puder compartilhar, ficaria grato!

**Comment by diego-silva** [comment]
Cara, o pessoal já tá usando a thread em #149 pra isso, acho que é melhor seguir centralizando lá…

**Comment by Joaovtrc** [comment]
Boa @diego-silva , my bad, não tinha visto esse fio!
