### ISSUE TITLE
[Dúvida] contrato de trabalho

### ISSUE THREAD

**Issue by vanessametonini** [DyegoCosta/trabalhando-remoto#19]
No caso pra quem é funcionário de empresa do exterior:
Algum de vocês tem um contrato de trabalho oficial? 
Como que se oficializa/formaliza essa relação empregado-empresa(internacional)?

**Comment by DyegoCosta** [comment]
@vanessametonini eu trabalho como PJ, então no meu caso existe um contrato oficial assinado por mim em nome da minha empresa e pela empresa que me contratou, igual trabalhar como PJ aqui no Brasil mesmo. Inicialmente me enviaram o contrato, eu assinei e enviei de volta (para os EUA), na renovação do contrato eu assinei lá no escritório deles pessoalmente.
Para trabalhar como pessoa física eu imagino que você tenha que ter um visto de trabalho do país em que o seu empregador está situado. Não tenho certeza de como funcionaria os impóstos nesse caso, mas com certeza pagaria os impostos brasileiros e talvez (a parte que não tenho certeza) os impóstos do país que está te empregando (no caso como pessoa física)
Recomendo sempre manter algum tipo de contrato oficial com qualquer empresa para que trabalhe, isso vai te dar uma certa segurança

**Comment by fabiolnm** [comment]
@DyegoCosta vc poderia anexar ao repositório o seu modelo de contrato PJ? 
Vc precisou fazer uma tradução juramentada? 
Vc tem lidado com burocracias como o Siscomex?

**Comment by shamanime** [comment]
Tenho as mesmas dúvidas do companheiro @fabiolnm.

**Comment by DyegoCosta** [comment]
@fabiolnm @shamanime acredito que não posso anexar o modelo pois o mesmo foi formulado pela empresa para qual presto serviço, vou confirmar e caso possa eu crio uma página na Wiki, e aviso vocês.
Quanto a tradução, até hoje não tive a necessidade de traduzir o contrato
Siscomex é para venda de mercadorias, não se aplica ao meu caso. No caso do SISCOSERV, que é prestação de serviço, também não se aplica para o meu caso pois:

```
São dispensadas da obrigação de prestar as informações:
- as pessoas jurídicas optantes pelo Regime Especial Unificado de Arrecadação de Tributos e Contribuições devidos pelas Microempresas e Empresas de Pequeno Porte -(Simples Nacional), e o Microempreendedor Individual (MEI) de que trata o § 1ºdo art. 18-A da Lei Complementar nº 123, de 14 de dezembro de 2006, , desde que não tenham utilizado mecanismos de apoio ao comércio exterior de serviços, de intangíveis e demais operações (PROEX, ACC eou ACE); e
- as pessoas físicas residentes no País que, em nome individual, não explorem, habitual e profissionalmente, qualquer atividade econômica de natureza civil ou comercial, com o fim especulativo de lucro, mediante venda a terceiro de bens ou serviços, desde que não realizem operações em valor superior a US$ 30,000.00 (trinta mil dólares dos Estados Unidos da América), ou o equivalente em outra moeda, no mês.
```
