### ISSUE TITLE
Melhor transfer digital

### ISSUE THREAD

**Issue by guilherme6191** [DyegoCosta/trabalhando-remoto#27]
Olá, Dyego. 

Primeiro, parabéns pelo repo, muito bom como você reuniu várias informações relacionadas a trabalho remoto.

Tenho uma pergunta e agradeceria se puder responder.
Para receber de fora, utilizando sistemas como o Paypal, qual sistema você recomenda? Ouvi dizer que as taxas e a conversão de Dolar para Real deles são bem caras. Ouvi falar do transferwise, mas não tenho certeza se da pra utilizar para fins profissionais.

Muito obrigado!

Att,
Guilherme

**Comment by DyegoCosta** [comment]
Eu particularmente nunca utilizei nenhuma forma de pagamento digital para fins profissionais, sempre utilizei transações bancárias.

O @igorbozato já utilizou diversos, ele pode dar uma melhor impressão dos serviços disponíveis.

**Comment by igorbozato** [comment]
A melhor opção que encontrei foi o Xoom (recentemente comprado pelo
PayPal), barato e rápido, em horário comercial o dinheiro pode cair na sua
conta em minutos.

**Comment by guilherme6191** [comment]
Obrigado, Dyego e Igor, vou dar uma olhada.

Abraço!

**Comment by ericdouglas** [comment]
@igorbozato poderia explicar por gentileza como você faz para receber pelo Xoom?

Aqui só vejo opção de envio, nada de recebimento.

**Comment by jonataa** [comment]
Eric, é a empresa que faz o envio, você só precisa passar o número da conta
no banco e o CPF, o dinheiro cai direto.

Em sáb, 6 de ago de 2016 às 19:40, Eric Douglas <notifications@github.com>
escreveu:

**Comment by igorbozato** [comment]
@ericdouglas como o @jonataa disse, você precisa passar as instruções de envio para a empresa.

**Comment by ericdouglas** [comment]
@jonataa @igorbozato muito obrigado pessoal! :smile:

**Comment by lcguida** [comment]
Ressucitando esse assunto, visto que se passou algum tempo, algum de vocês já tentou Trasnferwise?
Eu moro atualmente na França e uso pra enviar dinheiro pra minha conta pessoal.

Possivelmente volto ao Brasil e pensei em usar para receber quando estiver por lá.

**Comment by AndreiCalazans** [comment]
Após algumas pesquisas conclui que um dos melhores serviços é do payoneer, ele tem a melhor taxa final. A conversão é boa.  No final vc consegue receber e pagar 3% para ter o dinheiro na sua conta no Brasil. 
Ja usei bitwage e paypal antes, bitwage consegue taxas de 4~5%.

**Comment by rubemz** [comment]
@yuriploc Eu estou tentando usar. Mandei os documentos para o cadastro e estou esperando o ok final. Depois compartilho como foi a experiência.

**Comment by AndreiCalazans** [comment]
> @AndreiCalazans A taxa do payoneer é fixa em 3%?
> Meu interesse pelo Husky é justamente pela taxa ser fixa (e transparente) em 4%. @rubemz Assim que puder compartilhar aqui, seria bacana!

Sim, para transferências vindo do EUA.

**Comment by lcguida** [comment]
@yuriploc Isso depende da empresa também. 

Existem duas etapas: o dinheiro chegar no Payoneer e você transferir o  dinheiro do Payoneer para a sua conta.

Na primeira etapa, vai depender da empresa que te paga. Se ela tiver uma conta no Payoneer, não tem taxa. Se for via transferência bancária, é até 1%. Existem ainda outros métodos (https://www.payoneer.com/fees/)

Já para transferir o dinheiro para a sua conta, a taxa é até 2%.

Então, quando se fala que é 3%, é o 1% do pagamento mais o 2% da transferência.

@AndreiCalazans 

> Após algumas pesquisas conclui que um dos melhores serviços é do payoneer, ele tem a melhor taxa final. A conversão é boa. No final vc consegue receber e pagar 3% para ter o dinheiro na sua conta no Brasil.

Você tem noção de mais ou menos quanto fica o spred deles (se existe) ? OU eles usam a cotação real do dia?

**Comment by AndreiCalazans** [comment]
> Você tem noção de mais ou menos quanto fica o spred deles (se existe) ? OU eles usam a cotação real do dia?

@icguida 
Eles usam a cotação real do dia. Foi o que eu mais gostei 😄

**Comment by rubemz** [comment]
Semana passada eu recebi pela primeira vez pelo Husky (conta PJ). A única taxa que me cobraram foram 3,6% (eu acredito que o normal é 4% mas um amigo me passou um código de indicação e a taxa caiu), sem spread na taxa de conversão do dólar. Três dias depois da transferência (wire transfer) feita nos EUA a transação apareceu no App da Husky. No outro dia já tinha caído na minha conta. No geral achei o serviço bom.
