### ISSUE TITLE
Melhor banco para receber pagamento do exterior

### ISSUE THREAD

**Issue by thiagogabriel** [DyegoCosta/trabalhando-remoto#28]
Comecei a trabalhar remoto para o exterior a pouco tempo e gostaria de saber sua opinião sobre os bancos para receber como pessoa jurídica. O que você tem usado? Recomenda ter conta em mais de um banco? Estou inclinado entre o Santander Empresarial que prece ter a melhor conversão e o Citi que parece ser mais simples de fazer a transação.

Obrigado.

**Comment by jonataa** [comment]
Tive uma experiência bacana com o Banco do Brasil, inclusive como PF também. Você libera o ordem de pagamento através do site (antes das 17h) e cai na sua conta no mesmo dia. Eles seguem o câmbio do Banco Central, se não estou enganado (diferente de alguns bancos que possui sua própria cotação).

**Comment by kaiomagalhaes** [comment]
Eu utilizo o Itau, a taxa de conversão costuma ser entre 20 e 26 centavos.
Para receber é fácil e rápido, as vezes menos de 4 horas se você fizer
antes das 16 horas e dá pra fazer pela internet.

**Comment by valdir-pereira** [comment]
Eu to fazendo com o Santander, como Pessoa Física mesmo. Preciso ir ao banco assinar uns papeis lá todo mês, mais o dinheiro cai na conta no mesmo dia tambem.

**Comment by thiagogabriel** [comment]
@valdir-pereira você sabe o valor do dólar na última transação pelo Santander vs o valor pelo Banco Central?

**Comment by valdir-pereira** [comment]
@thiagogabriel Pelo Santander dia 14 agora deu 3,7. Acabei de ver o Banco Central no mesmo dia deu 4,02 . http://www4.bcb.gov.br/pec/taxas/port/ptaxnpesq.asp?id=txcotacao
Mais será que algum banco paga o valor da cotação do banco central ? 
O Santander eu pago uma taxa de R$ 60,00 de cambio.

**Comment by kaiomagalhaes** [comment]
@valdir Itau esta exatamente igual =/

**Comment by joaocunha** [comment]
Dependendo do local da fonte, vale mais a pena usar o TransferWise que bancos.

**Comment by thiagogabriel** [comment]
Pelo visto a cotação do Santander Empresarial é melhor, só que a taxa de transação é R$180. Alguém recebeu recentemente por ele pra saber se continua nessa faixa?
https://github.com/DyegoCosta/trabalhando-remoto/wiki/Bancos#pessoa-jur%C3%ADdica

**Comment by valdir-pereira** [comment]
@thiagogabriel mandei um email pra Gerente do Santander aqui que tenho contato sobre a cotação desse Santander Empresarial, aguardar ela responder.

@kaiomagalhaes Qual a taxa que o Itau cobra sobra a transação !? De repente vou fazer uma conta lá pra receber. 

@joaocunha  Entrei no site da TransferWise parece ser bem interesante, sou meio receioso com alguns serviços assim, tenho que dar uma estudada melhor, voce recebe por eles? é de confiança?

**Comment by joaocunha** [comment]
@valdir-pereira não recebo por eles mas é extremamente confiável. Há serviços similares por aí, se quiser comparar.

**Comment by shamanime** [comment]
Eu tenho conta jurídica no BB mas para recebimento utilizo a Cotação (https://www.cotacao.com.br).

Quando a ordem de pagamento é recebida eles enviam um email automático de aviso, então eu observo o dólar e quando está favorável eu ligo e fecho em menos de 5 minutos, recebo o boleto de câmbio na hora e só preciso enviar a invoice pra eles. Dependendo do horário que eu fechar eles pagam no mesmo dia, se for muito tarde pagam na manhã do dia seguinte.

**Comment by kaiomagalhaes** [comment]
@valdir-pereira eles cobram entre 24 e 28 centavos do dolar e 60$ pela
transação

**Comment by fgrehm** [comment]
Não conhecia o TransferWise mas [vi isso aqui no site deles](https://transferwise.com/help/article/2002578/latin-america-transfers/brl-transfers#/Info):

## Information regarding BRL business payments

> TransferWise can only make personal payments to Brazil, we **_cannot currently make payments to BRL which are to or from a business account, both the sender and recipient must be a privately owned account of an individual_**. (The money for a BRL transfer cannot come from a trust fund account, or any type of third party account.)

--------

Não sei se entendi direito mas me parece que não rola de receber de / para uma conta de uma empresa. Se alguém já recebeu de uma empresa por eles da um grito ae :smile: :beers:

**Comment by joaocunha** [comment]
@fgrehm bom saber disso. Não sabia que rolava essa restrição, não.

**Comment by thiagogabriel** [comment]
Fiz uma conta do Santander empresarial e achei a cotação muito boa.
O dólar comercial estava 4.04 e consegui 4.005 no cambio com o Santander. O Itaú empresarial estava 3.84 na mesma hora.

**Comment by valdir-pereira** [comment]
@thiagogabriel voce pegou uma cotação Boa entao!! O foi preciso para fazer o Santander Empresarial, quais as taxas voce pagou nessa transação ?

**Comment by thiagogabriel** [comment]
@valdir-pereira CPF, RG, comprovante de endereço, documento de enquadramento no simples e cartão do CNPJ.
A conta PJ tem mensalidade de R$30 ou R$60 dependendo do que você precisa.
A taxa de cambio é R$150.
A única coisa estranha é que sumiu $30 nessa brincadeira. Estou vendo se descubro onde foi parar, porque o Santander falou que recebeu o valor sem os $30 e a empresa enviou o comprovante que enviou o valor e pagou uma taxa de $40 pra fazer o pagamento.

**Comment by thiagogabriel** [comment]
Update sobre os $30.
```
A despesa de banqueiro (neste caso USD 30,00) é um acordo comercial entre a sua empresa e o importador no exterior. Não é uma tarifa cobrada pelo Banco Santander.
...
As despesas são compartilhadas (SHA). Para que você receba aqui no Brasil o valor integral, As despesas da transferência precisam ser por conta do beneficiário no exterior (OUR).
Gentileza contatar o seu cliente no exterior e solicitar o complemento do valor, se necessário.
```

**Comment by morenopc** [comment]
Alguém conhece ou utiliza os serviços do [Banco Rendimento](http://www.rendimento.com.br/5151/op-google/cadastro-banco-rendimento.html)? Eu sempre utilizei o banco do Brasil para receber ordens de pagamento mas este mês sinto uma certa dificuldade. Os funcionários ficam me empurrando de agência para agência sem conseguir efetuar a transferência.

**Comment by shamanime** [comment]
@morenopc eu comentei [ali acima](https://github.com/DyegoCosta/trabalhando-remoto/issues/28#issuecomment-172933605) sobre a Cotação, que é a empresa do grupo Rendimento responsável por câmbio. A conta no Banco Rendimento não é necessária, você cadastra sua conta PJ de qualquer banco e eles fazem o pagamento. Se você mudar de banco, é só alterar o cadastro com eles. Os dados de pagamento que seu cliente usa não mudam.

**Comment by morenopc** [comment]
@shamanime obrigado. Eu não tinha ligado o Banco Rendimento ao site Cotação.

Assim com os dados que você passou "O spread é por volta de 15-19 centavos e $20 de taxa." Com o dólar a `R$3,25770 (google)` temos `$100 = R$325,77`. Descontando as taxas (média de 17 centavos e $20) `3,25770−0,17=3,0877*(100-20)=R$247,016` diferença de `R$78,75 (325,77-247,016)`. Claro que em relação a valores maiores a taxa melhora. Para `$1000 (3257,70−3025,946)` paga-se `R$231,75` de taxas.

Esses cálculos estão corretos?

**Comment by shamanime** [comment]
@morenopc Exemplificando com $1000 e os dados da minha última operação:

Dólar comercial R$ 3,2545.

Taxa cambial: R$ 3,13 (R$ 0,12 de spread).
Valor bruto: R$ 3.130 (1000 x 3,13).
Tarifa cobrada ($20) R$ 65,09 (20 x 3,2545).

Total recebido: R$ 3.064,91 (3.130 - 65,09)
VET (Valor efetivo total): R$ 3,0649 (3.064,91 / 1000)

IOF alíquota 0.

**Comment by morenopc** [comment]
Banco do Brasil - exemplificando com $1000 e os dados da minha última operação:

Dólar comercial R$ 3,2295 (BCB)

Taxa cambial: R$ 3,1980 (R$ 0,0315 de spread).
Valor bruto: R$ 3.198 (1000 x 3,1980).
IOF (0,38%) R$ 12,1524 (3198 x 0,38%).

Total recebido: R$ 3.185,85 (3198 - 12,1524)
VET (Valor efetivo total): R$ 3,1858 (3.185,85 / 1000)

Diferença de R$ 120,94 (3185,85 - 3064,91) em relação ao banco rendimento.

![taxas de cambio](https://cloud.githubusercontent.com/assets/577383/17742680/66b6cacc-6477-11e6-8b89-03281dc6d6a1.png)

**Comment by shamanime** [comment]
@morenopc ué, não entendi seu cálculo.

Você comparou o seu valor recebido com o meu, sendo que o dólar no cálculo tem valor diferente.
IOF deveria ser 1,1%, não?
BB não cobrou tarifa?

**Comment by joaocunha** [comment]
Dadas as proporções, a diferença deveria ser mais significativa ainda, pois o dólar estava 3 cents mais alto quando da operação do @shamanime.

**Comment by morenopc** [comment]
@shamanime o propósito do cálculo é encontrar a melhor solução para o recebimento de ordens de pagamento do exterior (comparação removida).

Até o momento os valores são exatamente esses caso seja gerada alguma nova cobrança vou atualizar os cálculos.

**Comment by morenopc** [comment]
É sempre bom lembra que:

> O Banco não pode, sem autorização do beneficiário, fazer a conversão da moeda estrangeira para reais (operação de câmbio) e creditar o valor em reais em sua conta, mesmo que seja correntista ou poupador.
> A lei determina que o beneficiário de uma ordem de pagamento em moeda estrangeira, para receber os reais, assine os instrumentos de formalização (boleto ou contrato de câmbio), conforme o artigo 23 da Lei nº 4.131, **exceto para as operações de até USD 3.000,00 ou do seu equivalente em outras moedas**.
> Afim de evitar atrasos, orientamos que conceda Autorização Permanente para Crédito em Conta, solicitada nas agências do Banco do Brasil.
> O limite de recebimento do valor depende da finalidade / natureza da ordem de pagamento. Para valores **acima de USD 3.000,00 como há necessidade de comprovação documental**, o limite será o valor em moeda estrangeira que constar no documento válido apresentado.
> O recebimento do valor em espécie, diretamente no caixa, é limitado a R$10 mil. Acima desse valor, somente poderá ser feito crédito em conta do beneficiário.

Em caso de dúvidas de uma olhada no reclame aqui
[google site:www.reclameaqui.com.br banco do brasil ordem pagamento exterior](
https://www.google.com.br/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:www.reclameaqui.com.br+banco+do+brasil+ordem+pagamento+exterior)

**Comment by brunocsousa** [comment]
Muito legal a discussão aqui galera... Estou na mesma situação e tenho conta jurídica no BB e no Itaú. Estou tentando conseguir a informação sem ter que ir pessoalmente a cada banco falar com os meus gerentes, mas está difícil. 
Assim que rolar eu coloco um comparativo aqui, mas aparentemente pelo que vi o pessoal aqui falando, o BB parece ser a melhor pedida no meu caso.

**Comment by brunocsousa** [comment]
Pessoal, tudo beleza?
Conforme prometido, segue abaixo o que rolou. 
Minha gerente do Itaú não soube me dizer como contratar o serviço. Um monte de gerente no banco e ninguém sabia me dar informação, ficavam um perguntando ao outro, experiência horrível. Fui ao banco duas vezes e não consegui a informação. Por isso, acabei desenrolando com o Itaú... achei meio pesadas as taxas e estou procurando uma alternativa mais em conta:

Usando o exemplo de USD$ 1,000.00

Banco Itaú
Dolar Comercial no dia/horario da cotação (Banco Central): R$ 3,37
Valor da Cotação pago pelo Itaú: R$ 3,19
Taxa Cambial/Spread (Cotação - Dolar Comercial): USD$ 0,18
Taxas do serviço ComExpress Itaú: R$ 135,00
IOF: 0

Custo Total para receber (Spread * R$ 3,37 + Taxas de Manuseio): R$ 764,00

**Comment by joaocunha** [comment]
@brunocsousa acho que não entendi teu cálculo. Entre spread e taxa de serviço o custo não deveria ter sido R$315,00?

**Comment by brunocsousa** [comment]
@joaocunha Completamente errado joão, já corrigi. Obrigado por avisar. Abs.

**Comment by fernando1957** [comment]
Não existe! O sistema bancário brasileiro (se é que se pode chamar assim) é um dos mais obsoletos, arcaicos, enrolados, caros e ineficazes de todo planeta. Os gerentes das agências mal sabem lidar com coordenadas internacionais (IBAN); muitos nem mesmo sabem do que se trata. Aliás, não tem um poder de decisão sequer...são como empergados de luxo. 
Em particular o BB e a CEF, são verdadeiros "elefantes brancos, ursos polares, chupa-cabra, bodes na sala, macaco drogado solto em loja de cristais", quando a questão é enviar ou receber dinheiro do exterior. Além de serem enrolados e incompetentes na matéria, o serviço (quando você consegue tratar), é o mais caro do planeta, complicado e moroso. Não é por menos que os bancos estrangeiros se mandaram do país. Isso sem falar no tal "internet banking" (o do BB chega a ser uma piada) que não funciona de jeito nenhum. É chave prá lá, senha prá cá, nome da mãe, CPF, data de aniversário, pen drive remota e o escambau. A coisa entra na pré-história, se comparados aos bancos estrangeiros. 
Na Europa (outro planeta), a coisa é super simples. Envio e recebo dinheiro de todos os países da UE, dos EUA, Austrália, Canadá, etc. Nenhuma burocracia, nada de IOF ou taxas absurdas, nada de "mesa de câmbio", nada de câmbio inventado (no Brasil, cada banco faz o seu ... é um carnaval). O BB chegou a se associar a uma empresa estrangeira para reemessas de dinheiro (Western Union), o que é um absurdo, principalmente sabendo que essa empersa cobra taxas absurdas de envio de dinheiro, sem contar que praticam um câmbio deles, ao seu bel prazer.
Nas contas da nossa empresa, aqui na Europa, entro com dois cliques (sistema tremendamente seguro) e faço o que quiser: FOREX, aplicação nas bolsas de valores de todo o mundo, compro e vendo ouro (commodities) e pago e recebo em cinco moedas diferentes, na mesma conta (é só escolher), de e/ou para qualquer lugar do planeta (menos Brasil), apenas preenchendo o formulário, no site, com os dados do favorecido e dois cliques para enviar.
Um exemplo da velocidade e da simplicidade do sistema bancário estrangeiro:
Um cliente nosso, lá da Austrália, nos enviou um e-mail perguntando se um artigo ainda estava disponível. Respondemos que sim. O cliente não disse mais nada ... em 5 (eu disse CINCO) minutos, o dinheiro estava na nossa conta na Itália. Agora se segura na cadeira, porque quem vive a realidade brasileira, nem vai acreditar: O cara entrou em uma agência bancária, próxima de onde estava (detalhe: não era o banco onde ele tem conta). No caixa, disse que queria efetuar um pagamento, passando apenas nossas coordenadas IBAN. O caixa pegou as coordenadas e o cara pagou 5.600,00 euros (a conversão é feita imediatamente), COM UM CARTÃO DE CRÉDITO ... isso mesmo!!! O cara pagou a conta, na Austrália, entrando em uma agencia de banco onde não tem conta e, usando seu cartão de crédito, enviou dinheiro para o outro lado do planeta.
Ahhh, os caixas eletrônicos. Aqui, entro em qualquer banco (mesmo não sendo o que tenho conta) e utilizo o caixa eletrônico para executar todas as operações que faria num caixa do meu banco. Depositar dinheiro é uma facilidade. Você entra em qualquer banco e lá está o caixa eletrônico. Nada de envelopes ... basta colocar o dinheiro e a máquina conta tudo, pede a confirmação do valor e envia o saldo total para onde vc quiser.
Quando o Brasil vai chegar nesse nível de eficácia??? Pelo andar da carruagem, NUNCA!!!

**Comment by fernando1957** [comment]
Agora, falando de receber (sacar) dinheiro, com cartão, no exterior. Até nisso, os bancos brasileiros são ruins...as taxas são absurdamente altas para cada operação. Sem falar nessa arbitrariedade que é o tal IOF. Se continuarem assim, em breve o Brasil vai definitivamente, regressar à pré-história.

**Comment by fernando1957** [comment]
Parte do meu extrato do BB (Banco de Bosta ... aliás, em termos de bancos brasileiros, todos são ... não salva um sequer): Saquei 500 euros num caixa eletrônico, na Itália. Ao câmbio do dia, deveriam ser R$ 1.653,71, mas ao invés disso, foram R$ 1.735,74, uma diferença de R$ 82,03 a favor do Banco do Brasil (câmbio extorsivo). Além disso, cobram o absurdo valor de R$ 110,74 de IOF, mais uma taxa (abusiva) de retirada no exterior (piada), de R$ 20,00. Somando tudo, cada 500 euros sacados na Europa, te custam (R$ 82,03 + R$ 110,74 + R$ 20,00), ou seja R$ 212,77 reais. Um cidadão chamado Dyego (com Y) Costa negativou meu comentário anterior. Das duas uma: ou é funcionário de uma dessas porcarias de bancos brasileiros ou é um nacionalista de bosta que acredita que ser patriota é tapar o sol com a peneira.
![bb](https://cloud.githubusercontent.com/assets/25768755/22943361/986614e2-f2ed-11e6-83d1-626971b00a62.JPG)

**Comment by fernando1957** [comment]
Agora, um pequeno demonstrativo da facilidade, da comodidade, da simplicidade (com muita segurança), do sistema de um banco europeu. Para entrar, bastam o nome de usuário e a senha (nada de tokens, nome da mãe, número de CPF, nome do pai, do papagaio, do gato, data de nascimento ... nada de códigos enviados por celular e nem autorizações especiais ... recebo e envio o quanto e quando quiser, esteja onde estiver). Pronto, você está dento do site! Gráfica simples, minimalista, onde você tem acesso a tudo (até uma criança entende). 
Na conta corrente, posso manter (dividir) meu saldo em QUATRO moedas diferentes (euros, dólares americanos, francos suiços ou esterlinas). Sou eu quem escolhe quanto quero manter de saldo em cada moeda. Basta fazer um FOREX que é imediato, muito simples e no ambiente do próprio site.
Ainda no site, posso operar em todas as bolsas importantes do mundo (exceto as brasileiras). Posso comprar e vender com dois cliques, títulos da APPLE, da BASF, da Coca-cola, Arcelor, Bayer, na bolsa italiana, inglesa, francesa, em Singapura, nos EUA ... onde quiser (menos no Brasil), etc. A compra e venda é feita em tempo real, dentro do site, e imediata. Compro ou vendo o título que imediatamente entra em carteira. Isso e muito mais. Compro ouro, prata, platina e escolho se quero manter em carteira ou receber o metal, sem pagar qualquer imposto ou taxa abusiva. Pago o que quiser, envio e recebo dinheiro de onde bem entender (menos do Brasil). Bastam, as coordenadas IBAN que aparecem lá em cima (cobri com uma tarja amarela por motivos óbvios). Isso é um mundo civilizado e não um planeta na pré-história.
![conto fineco](https://cloud.githubusercontent.com/assets/25768755/22945926/386797ba-f2f6-11e6-9ac0-add8ced2cf38.JPG)

**Comment by DyegoCosta** [comment]
Pessoal, como eu imagino que todos saibam, este repositório tem o único e simples objetivo de ajudar quem precisa de informações sobre trabalhar remoto. No caso deste issue, o objetivo é trazer informações que ajudem a quem precisa trazer dinheiro do exterior para o Brasil.

Aqui não é o portal do G1 para virem chorar suas mágoas ou contar vantagens, então por favor mantenham seus comentários civilizados e com o foco em ajudar o próximo.
