### ISSUE TITLE
Declaração de imposto de renda

### ISSUE THREAD

**Issue by herodrigues** [DyegoCosta/trabalhando-remoto#29]
Olá, pessoal

Atualmente eu sou desenvolvedor web e trabalho para uma pequena startup americana através do Upwork.
O guia está bem explicado em relação a declaração de impostos, mas eu ainda tenho algumas dúvidas.

- Posso declarar meus rendimentos somente na declaração anual?
- Eu transfiro meu dinheiro para o PayPal e depois para minha conta corrente, sendo assim eu perco uma grana (uma boa grana) por conta da taxa de conversão do PayPal. Tenho que declarar o valor recebido na minha conta corrente ou no PayPal?
- Levando em conta que trabalho para uma empresa no exterior que não tem representatividade no Brasil, como fica meus direitos trabalhistas?
- Fiz uma simulação simples no carnê-leão e o valor de imposto que devo pagar é um tanto quanto alto pra alguém que não vai receber nada em troca (em relação a direitos trabalhistas, eu acho). Alguma outra alternativa para minimizar essa tributação?

**Comment by vanessametonini** [comment]
Oi Henrison, segue minha experiência com os itens citados:

> Posso declarar meus rendimentos somente na declaração anual?
Acredito que sim, porém prepare-se para pagar uma bolada de imposto de renda. Com o carnê leão vc paga mensal porem em "pequenas" doses.

> Eu transfiro meu dinheiro para o PayPal e depois para minha conta corrente, sendo assim eu perco uma grana (uma boa grana) por conta da taxa de conversão do PayPal. Tenho que declarar o valor recebido na minha conta corrente ou no PayPal?
Eu declarei o valor liquido, vamos ver como vai ser esse ano quando fechar o IR.

> Levando em conta que trabalho para uma empresa no exterior que não tem representatividade no Brasil, como fica meus direitos trabalhistas?
Você fica sem direitos trabalhistas. Na verdade vc pode escolher qual direito é o melhor para você (do seu país ou do país da empresa), porém caso vc queira processar a empresa por algum direito "infringido" vc terá que abrir um processo internacional que é o mais caro que existe, ou seja completamente inviável para quem é apenas um fornecedor de "mão de obra".

> Fiz uma simulação simples no carnê-leão e o valor de imposto que devo pagar é um tanto quanto alto pra alguém que não vai receber nada em troca (em relação a direitos trabalhistas, eu acho). Alguma outra alternativa para minimizar essa tributação?
é dureza mesmo, se passa de mais de 5k, fudeu. não sei te dizer se tem algo que compensa mais. To esperando ansiosamente qual vai ser o IR esse ano (impostos devidos e restituição)..

Bom nao ajudei muito mas compartilhei um pouco aqui da minha experiência e expectativa. :B

**Comment by shamanime** [comment]
Não consideraram fazer um contrato PJ?Qual o lado negativo do PJ?Trabalho remoto também, usando CNPJ e a carga tributária é bem menor (6% com o Simples Nacional). Depois faço distribuição de lucro. Fica tudo certo dentro da legislação. 


    _____________________________

**Comment by joaocunha** [comment]
@shamanime rola passar um TL;DR do Simples aí? :)

**Comment by herodrigues** [comment]
Obrigado @vanessametonini! Ajudou bastante!

@shamanime eu estava procurando algo dentro da legislação também onde eu não saísse tão prejudicado. Andei pesquisando sobre microempreendedor individual, mas desenvolvedores web não entram nessa. Poderia explicar melhor sobre isso?

**Comment by shamanime** [comment]
@joaocunha e @herodrigues,

O melhor a se fazer é bater um papo com um bom contador. Ele vai te ajudar a entender corretamente o que pode ser feito para diminuir a carga tributária sem trapaças.
O Simples Nacional diminui a alíquota de alguns CNAEs das empresas optantes, é bastante importante selecionar os CNAEs corretamente para poder se enquadrar.
Realmente algumas atividades ligadas diretamente ao que fazemos não se enquadram, mas há outras relacionadas que permitem o enquadramento.

Novamente, a parte do bom contador é importante pra não ter dor de cabeças caso haja fiscalização, e pra não ter problemas com IR depois.

**Comment by herodrigues** [comment]
Valeu pelas dicas de todos! 

EU vou atrás de um contador pra resolver essa situação e depois volto aqui com minha solução.

:smile:

**Comment by ericdouglas** [comment]
Prestação de serviço de desenvolvimento de software o imposto é de 17,5% + 2% de ISS.

https://www.contabilizei.com.br/contabilidade-online/tabela-simples-nacional/

**Comment by vrbrito** [comment]
@herodrigues Herinson, pode me passar um contato seu para tirar algumas dúvidas? Também estou trabalhando via Upwork e fiquei bem perdido com alguns aspectos do IR.

**Comment by herodrigues** [comment]
@vrbrito leia minha resposta aqui https://github.com/DyegoCosta/trabalhando-remoto/issues/81

**Comment by vrbrito** [comment]
@herodrigues Sou funcionário CLT e faço uns bicos no Upwork, então tenho dúvidas um pouco mais pontuais com relação a declaração do IR via Carnê Leão. Não tenho que me preocupar muito com INSS, porque já pago o teto via empregador formal, mas minhas principais dúvidas são:

1) Se eu decidir pagar só na declaração de ajuste, à vista, incidirá multa/juros sob meu imposto devido?
2) O carnê leão não considera minha alíquota de empregado na hora de declarar, devo declarar com a alíquota abaixo e simplesmente aguardar a declaração de ajuste pra corrigir isso pra cima? (Não sei se você viveu o mesmo caso)
3) Você declara os valores do Upwork conforme vão caindo na sua conta do site ou só quando realmente transfere pro Brasil?
4) Quanto as deduções possíveis (1/5 despesas de aluguel, condo, etc), você declara inclusive meses em que você não faturou ou apenas aqueles em que você recebeu pagamentos? Como vira e mexe passo alguns meses trabalhando pra receber só no final, fiquei na dúvida quanto a este ponto.

Agradeço pela resposta até então.

**Comment by herodrigues** [comment]
As dicas nesse repo sobre PJ e impostos servem basicamente pra quem trabalha exclusivamente como freelancer.
Quem recebe valors baixos, nem precisa se preocupar com isso. É só seguir as regras de quem já paga carnê-leão.

No mais, todas as suas dúvidas tem respostas no [README](README.md)

**Comment by vrbrito** [comment]
@herodrigues Não, não tem, mas agradeço pelo seu tempo em me responder. :+1:

**Comment by herodrigues** [comment]
Arrisco dizer que toda informação sobre trabalhar remotamente pode ser encontrada nesse repo.

1. https://github.com/DyegoCosta/trabalhando-remoto/issues/35#issuecomment-269991260 e https://github.com/DyegoCosta/trabalhando-remoto/issues/29#issuecomment-183561817
2. Não é o meu caso, pois não sou CLT
3. https://github.com/DyegoCosta/trabalhando-remoto/blob/master/README.md#imposto-de-renda
4. https://github.com/DyegoCosta/trabalhando-remoto/issues/58#issuecomment-372104063

**Comment by vrbrito** [comment]
@herodrigues Se não se importar em tirar uma dúvida, agradeceria bastante.
Estou abrindo minha PJ agora e sigo trabalho com o upwork que era o seu caso inicialmente, correto? Isso ainda se aplica? Então, minha principal dúvida é, ao emitir a nota fiscal, tenho que declarar o valor do contrato ou apenas aquilo que recebi pós descontos do Upwork? Porque isso muda muito o valor final, já que significaria que estou pagando imposto sobre um valor que nem estou recebendo.

**Comment by herodrigues** [comment]
Aparentemente, a Receita só se preocupa se você está pagando imposto sobre o que recebe na conta PJ: https://github.com/DyegoCosta/trabalhando-remoto/issues/58#issuecomment-495347131

Uma contadora aqui na minha cidade também me falou algo parecido em relação ao texto inserido na descrição das notas fiscais e o serviço prestado de fato.

**Comment by vrbrito** [comment]
@herodrigues Você ainda trabalha via Upwork? Como você sabe, as taxas lá são bem relevantes, será que dá pra declarar só o que recebo? Seria este o correto? Não entendi muito seu comentário sobre o texto.

**Comment by herodrigues** [comment]
Se estiver errado, então todos estamos. Mas o comentário que linkei diz o contrário.

Sobre as notas, eu quis dizer que ela me falou que a descrição da nota não precisa ser exatamente o que você fez em detalhes. Por exemplo, "desenvolvi um site para cliente X" ao invés de "desenvolvi um site usando tecnologia A com apoio de fulano para resolução do problema B na plataforma C".

Fiz uma analogia com essa situação já que a Receita/Prefeitura só se importa realmente com os valores recebidos no Brasil e se foi lançada alguma nota correspondente ao valor desse serviço foi prestado.
