### ISSUE TITLE
Adicionar informações sobre impostos

### ISSUE THREAD

**Issue by DyegoCosta** [DyegoCosta/trabalhando-remoto#3]

**Comment by henrich-m** [comment]
http://www.arcos.org.br/artigos/o-iss-nas-importacoes-e-exportacoes-de-servicos/

Citando: 
     O serviço prestado fora do território brasileiro, por contribuinte residente no Brasil, para tomador residente no exterior e com resultado também no exterior é isento da tributação do ISS;

    O serviço prestado em território brasileiro, por contribuinte residente no Brasil, para tomador residente no exterior, cujo resultado se verifique no exterior é isento do ISS;

    O serviço prestado, em território brasileiro, por contribuinte residente no Brasil, para tomador residente no exterior, cujo resultado se verifique em território brasileiro, não é isento da tributação pelo ISS, por não ser enquadrado na definição de serviços exportados.

**Comment by fgrehm** [comment]
Não sei se seria nessa parte de impostos mas vale mencionar o carnê leão para quem não é pessoa juridica

**Comment by DyegoCosta** [comment]
@henrich-m pontos importantes, serão mencionados

**Comment by DyegoCosta** [comment]
@fgrehm não estou familiarizado com os impostos de PF, se você puder mandar um PR com o que souber será muito bem-vindo!
