### ISSUE TITLE
SIte de avaliação das empresas

### ISSUE THREAD

**Issue by igorshiohara** [DyegoCosta/trabalhando-remoto#33]
Poderia adicionar alguns sites que avaliam as empresas. Sei somente do [glassdoor](https://www.glassdoor.com/index.htm)

**Comment by ftonato** [comment]
@igorshiohara legal, eu conheço o [Love Mondays](https://www.lovemondays.com.br/), é brasileiro, mas bem útil :)

**Comment by DyegoCosta** [comment]
Valeu @igorshiohara e @ftonato! Adicionei suas sugestões em https://github.com/DyegoCosta/trabalhando-remoto#avalia%C3%A7%C3%B5es-de-empresas
