### ISSUE TITLE
Indicação de contadores para abertura de empresa

### ISSUE THREAD

**Issue by ericofusco** [DyegoCosta/trabalhando-remoto#36]
Alguém poderia passar indicações de contadores, de preferência em São Paulo, que já tenham experiência com esse tipo de situação ? 

Atualmente trabalho como full stack developer remotamente como pessoa física para uma empresa que só possui negócios nos EUA, solução não é utilizada no Brasil. Gostaria de abrir uma empresa e receber dela como PJ.

Tenho feito algumas pesquisas e vejo várias informações do pessoal recomendando abrir a empresa, mas nada muito mais detalhado nesse sentido, e não vejo nenhum serviço de contabilidade que entenda bastante disso. (Criação de contrato formal, quais impostos são isentos baseado no tipo de prestação de serviço remoto para o exterior, qual a melhor forma de criar a empresa, etc..)

Muito obrigado.

**Comment by ericdouglas** [comment]
@ericofusco Não utilizei [esse serviço](https://www.contabilizei.com.br/) pois não tem na minha cidade, mas se tivesse iria tentar.

Entra em contato com eles e vê se te atende. :smile:

**Comment by ygorlazaro** [comment]
@ericdouglas @ericofusco  eu uso o Contabilizei desde fevereiro pra minha empresa, e eles funcionam muito bem sim. Vale bastante a pena, e cobre SP!

Aliás, se quiser, eu posso mandar um invite que dá dois meses de descontos, pra você e pra mim :smile:

**Comment by joaocunha** [comment]
@ygorlazaro make it two :)

**Comment by ygorlazaro** [comment]
@joaocunha enviado!

**Comment by kaiomagalhaes** [comment]
@ygorlazaro manda pra mim:

me@kaiomagalhaes.com

**Comment by ygorlazaro** [comment]
@kaiomagalhaes tá lá!

**Comment by ericofusco** [comment]
Opa, muito obrigado galera.

@ygorlazaro Meu e-mail: ericopfusco@gmail.com :)

**Comment by ygorlazaro** [comment]
@ericofusco foi!

**Comment by clmadrazo** [comment]
@ygorlazaro poderia passar para mim?

**Comment by zanquini-lopes** [comment]
> @ericdouglas @ericofusco eu uso o Contabilizei desde fevereiro pra minha empresa, e eles funcionam muito bem sim. Vale bastante a pena, e cobre SP!
> 
> Aliás, se quiser, eu posso mandar um invite que dá dois meses de descontos, pra você e pra mim 😄

Manda o invite
