### ISSUE TITLE
Diferença entre trabalho remoto e home office

### ISSUE THREAD

**Issue by clucasalcantara** [DyegoCosta/trabalhando-remoto#40]
Vocês não acham que deveria constar uma seção explicando a diferença entre trabalhar remoto e trabalhar em regime home office?

**Comment by DyegoCosta** [comment]
@clucasalcantara você poderia explicar quais são as diferenças?

**Comment by clucasalcantara** [comment]
Opa @DyegoCosta , Trabalho remoto é quando o colaborador tem como responsabilidade principal as datas de entrega e como requisito uma carga horária diária (8h por exemplo) podendo ser consumida em qualquer horário ou até mesmo em blocos (2h de madrugada, 3h a tarde e 3h a noite por exemplo).

Já no regime home-office, os horários do colaborador são comerciais ou pré estabelecidos e ele deve estar disponível nestes horários, porém do conforto da sua casa.

**Comment by DyegoCosta** [comment]
@clucasalcantara de onde são essas definições?

De qualquer forma não sei se seria interessante incluir no repo pois não devem ser definições válidas em âmbito internacional (home office vs remote job)

**Comment by clucasalcantara** [comment]
São de alguns artigos, posso te passar depois. Mas tranquilo, me convenceu :P Lá fora remote = home office. Vou fechar a issue :)
