### ISSUE TITLE
Como funciona o processo de pagamento feito por empresas estrangeiras?

### ISSUE THREAD

**Issue by Bruno-Furtado** [DyegoCosta/trabalhando-remoto#51]
Pessoal,

Moro no Brasil e recebi uma proposta de trabalho home-office de uma empresa estrangeira.
Esta empresa fará os pagamentos mensalmente (dólar americano) na minha conta corrente de pessoa física no Brasil.

Li todo material disponível neste repositório mas gostaria de contextualizar um cenário fictício e verificar com vocês se há alguma falha de interpretação da minha parte.

## VALORES

- Dólar comercial: R$3,183
- Cotação do banco: R$3,08
- Tarifa de transação de fechamento de câmbio: R$60,00
- Manutenção de conta corrente: R$40,00

## ETAPAS

**1.** A empresa efetua o pagamento de $5.000 para minha conta corrente de pessoa física no primeiro dia útil do mês de novembro.

**2.** O meu banco recebe esse valor e aplica sua cotação do dólar, gerando um valor inicial de R$15.400,00. Este é o valor recebido bruto e, geralmente, cai na minha conta corrente entre 2 a 5 dias úteis após o pagamento da empresa.

**3.** No momento em que este valor cai na minha conta corrente, eu utilizo o software do Carne Leão para legalizar a situação junto a receita. A base de cálculo é o valor bruto de R$15.400,00, onde é cobrada a alíquota efetiva de 21,67% (mesmo estando na faixa dos 27,5%) segundo [este simulador oficial da receita](http://www26.receita.fazenda.gov.br/irpfsimulaliq/private/pages/simuladoraliquota.jsf). É gerada então um boleto onde devo arcar com a despesa de R$3.337,30, efetuando o pagamento até o último dia útil do mês de novembro.

**4.** Ao final, calculando as tarifas do banco (fechamento de câmbio e mensalidade) e o carne leão, tenho o valor líquido de R$11.962,70.

## DÚVIDAS

**A)** Existe alguma falha de interpretação com relação aos passos citados anteriormente? Estou me esquecendo de algo?

**B)** O simulador do carne leão cita a previdência oficial. Ela é obrigatória ou opcional?

**C)** Pagando o carne leão mensalmente, eu preciso declarar esses valores no meu imposto de renda anual? Se sim, eu vou precisar pagar mais algum imposto para o governo?

**Comment by fabiolnm** [comment]
A. Há algumas deduções legais para o carnê-leão:
* número de dependentes
* previdência oficial
* caso trabalhe em casa, vc pode declarar receitas e despesas no Livro-caixa. 1/5 de despesas como aluguel, condominio, luz, telefone, internet, material de limpeza, podem ser usadas como deduções legais (http://www.portaldecontabilidade.com.br/obrigacoes/livrocaixa.htm).

O pagamento é o último dia útil do mês posterior ao que vc recebeu (dezembro).

B) Sim, http://www.previdencia.gov.br/servicos-ao-cidadao/todos-os-servicos/gps/tabela-contribuicao-mensal/

Vc pode escolher pagar 11% do salário mínimo, porém isso não dá direito a aposentadoria por tempo de contribuição. Ou 20% do teto da remuneração (20% de 5.531,31 = 1.106,26)

Vc pode gerar a guia aqui: http://www.previdencia.gov.br/servicos-ao-cidadao/todos-os-servicos/gps/

Esteja atendo ao mês de competência. O salário que vc recebeu em novembro é referente ao que trabalhou no mês de Outubro. A data de vencimento da GPS acusa se vc preencheu o mês de competência corretamente.

C) No IR 2018, vc vai importar o Livro Caixa para o Imposto de Renda. Para essa faixa de ganhos, vc terá cerca de R$ 5.000,00 a restituir. Quanto maiores forem as deduções legais (despesas com saúde, educação, etc), maior o valor da restituição. Vide simulação: https://github.com/DyegoCosta/trabalhando-remoto/issues/37#issuecomment-271125762. 
Se vc enviar a declaração de IR logo no começo de março, por volta de junho/julho de R$ 2018 a restituição cai na sua conta bancária.

**Comment by fabiolnm** [comment]
Outra dica: se houver a possibilidade, peça para a empresa te pagar usando TransferWise. Até o momento, dos serviços que experimentei, é o que morde a menor fatia dos rendimentos recebidos (maior cotação / menores taxas).

**Comment by Bruno-Furtado** [comment]
@fabiolnm, muito obrigado!

## DÚVIDAS

**B)** Então eu preciso utilizar o software do Carne Leão e gerar a guia GPS pelo link que você compartilhou? Todo mês foi precisar realizar essas 2 ações?

**D)** Não há IOF, correto?

**E)** Ótima sugestão sobre a TransferWise!  Na issue #28 a galera comenta sobre esse serviço mas citam que ele só pode ser utilizado de pessoa física para pessoa física. Isso ainda é uma limitação? [Este link](https://transferwise.com/help/article/2002578/latin-american-transfers/brl-transfers#/Info) cita o seguinte trecho:

> Payments to Brazil can only be personal payments. Both the sender and recipient must be a privately owned account of an individual. The money for a BRL transfer cannot come from a business account,  trust fund, or any type of third party account and it can not be sent to a business in Brazil.

**Comment by fabiolnm** [comment]
B. Sim. A GPS vence no dia 15 do mês que vc recebe. O Carnê-Leão no ultimo dia útil do mês seguinte.

D. Não entendi.

E. Sim. Caso vc tenha abertura para negociar a forma de transferência e a empresa estiver disposta a fazer os pagamentos dessa forma (PF-PF), é o melhor custo benefício. De outro modo, caso tenha que ser PJ->PF ou PJ->PJ, e vc descobrir uma forma menos cara de fazer a transferência, compartilhe aqui na issue, será muito útil a todos que visitam este repositório.

**Comment by Bruno-Furtado** [comment]
@fabiolnm, show!

## DÚVIDAS

**A)** 👍

**B)** 👍

**C)** 👍

**D)** Peço desculpas pela minha falta de conhecimento mas gostaria de saber se os bancos também incluem a tarifa de IOF.

**E)** 👍

**F)** Em um cenário onde eu opte por trabalhar como PJ. Meu custo com contador é baixo (R$69,00/mês com a [Contabilizei](https://www.contabilizei.com.br/)), alíquota da nota fiscal é de 16,5% e a mensalidade de conta corrente é zero ([Banco Inter](bancointer.com.br)). Não seria mais vantajoso PJ ao invés de PF?

**Comment by fabiolnm** [comment]
D. Não sei responder

F. Depende. 

O que mais pesa para PF é justamente o custo com o INSS, que vc minimiza optando pela alíquota de 11%. Vc tem que fazer simulações para ver se, ao considerar as deduções legais / restituição, etc, a carga tributária de PF é vantajosa perante a responsabilidade em vc abrir / manter um PJ. A partir de um certo valor (acima de 10 mil, com certeza PF se torna desvantajoso).

Atente também que em 2018 as regras do Simples mudam, e a carga tributária vai aumentar muito para empresas com pro-labore menor que 28%. Por via das dúvidas, o Lucro Presumido é sempre a modalidade menos complicada de trabalhar.

**Comment by thiagogabriel** [comment]
D) Fiz câmbio no Santander semana passada e não paguei IOF. Um amigo meu fez essa semana e pagou. Pode ser que tenha mudado recentemente.

**Comment by Bruno-Furtado** [comment]
Com relação as cotações de câmbio praticadas pelas instituições financeiras, o Banco Central disponibiliza um ranking com a média mensal dos valores praticados [neste link](https://www.bcb.gov.br/rex/vet/index.asp).

## FILTROS:

**1. Qual o tipo de operação?** Transferencias pessoais
**2. O que eu quero?** Receber
**3. Qual a moeda?** DOLAR DOS EUA
**4. De qual país?** ESTADOS UNIDOS
**5. Quanto?** 3000

## RESULTADOS

Li um pouco a respeito e achei interessante a recomendação de um economista que sugere a análise dos últimos 6 meses (tem um botão onde é possível visualizar todo o histórico de cotações). Ele também cita que as instituições com baixo número de operações mensais (menos que 100) não são bons parâmetros de comparação pois suas cotações podem ter sido realizadas em um intervalo de tempo curto onde o dólar teve alta.

Diante deste cenário notei que o [Banco Rendimento](http://www.rendimento.com.br/) e o [Banco Paulista](https://www.bancopaulista.com.br/) se destacam.

As tarifas de manutenção de conta e de transferência TED são altas mas as diferenças da cotação do câmbio são grandes quando comparadas aos bancos de maior porte. Vou fazer um estudo mais detalhado para verificar se vale a pena utilizar um banco alternativo para recebimento.

### Banco Rendimento

O Banco Rendimento vêm apresentando bons resultados nos últimos 4 anos e tem se demonstrado uma instituição financeira bem consolidada, conforme apresentado [neste link](https://bancodata.com.br/relatorio/rendimento/).

**Manutenção de conta:** R$100,00
**Tarifa de fechamento de câmbio:** Não sei
**TED:** R$50,00

### Banco Paulista

O Banco Paulista também se mostra uma instituição financeira confiável, conforme [este link](https://bancodata.com.br/relatorio/socopa/).

**Manutenção de conta:** Não sei
**Tarifa de fechamento de câmbio:** Não sei
**TED:** R$25,00

**Comment by Bruno-Furtado** [comment]
@fabiolnm,

Uma alternativa ao [TransferWise](transferwise.com) é o [Payoneer](https://www.payoneer.com/main/).

Eles cobram 1% quando a empresa transfere o pagamento mensal para sua conta no Payoneer.

Para transferir do Payoneer para sua conta bancária no Brasil é cobrada a taxa de 2%.  O Payoneer realiza a conversão de USD para BRL utilizando o câmbio médio de mercado.

Não senti muita confiança na conversa com a atendente. Caso alguém utilize o serviço, sinta-se a vontade para compartilhar a experiência.

**Comment by pablo-sg-pacheco** [comment]
Eu estou tentando agora pelo [Bitwage](http://bitwage.com/). Acabei de receber pela primeira vez e o dinheiro ainda está em processo de ser depositado na minha conta bancária, mas parece que tudo está indo bem. Até agora parece que fui cobrado apenas 1%

Quando terminar todo o processo eu coloco aqui

**Comment by rubemz** [comment]
@Bruno-Furtado eu uso o Payoneer e sempre funcionou muito bem. Utilizei o cartão de crédito deles no exterior e transferi valores para a minha conta bancária sem nenhum problema até agora.

**Comment by Bruno-Furtado** [comment]
@rubemz,

As tarifas são aquelas mesmo? (1% quando a empresa transfere para sua conta Payoneer e 2% quando você transfere para sua conta corrente no Brasil)?

O câmbio médio do mercado é utilizado para conversão?

**Comment by rubemz** [comment]
@Bruno-Furtado Sim, as tarifas tem sido essas. 

Com relação ao câmbio sempre são alguns centavos a menos que a cotação do dia, não sei bem a regra. Por exemplo hoje eu consegui uma conversão de 1 USD = 3,11 BRL

**Comment by pablo-sg-pacheco** [comment]
Pessoal, só queria aproveitar e dizer que usei o [bitwage](www.bitwage.com) e foi uma maravilha.
No total, incluindo a transferência pra minha conta bancária, só perdi 1%!

Eu recebi o pagamento no dia 5/10/2017 em Euros e a taxa de conversão foi: 1 EURO = 3,67

**Comment by copercini** [comment]
Alguém já recebeu pelo https://www.cotacao.com.br ? Parece ser do mesmo grupo do Banco rendimento e achei fácil criar uma conta e utilizar, taxa de 20usd por recebimento em dólares, cotação desconhecida, mas por ser do Rendimento acredito que seja boa

**Comment by shamanime** [comment]
Eu só recebo com eles. A diferença costuma ser de uns 15 centavos do valor atual do dólar. Eles possuem um sistema online pra fechar a ordem, lá tem a cotação, mas é só pra clientes cadastrados. 

Nada a reclamar, atendimento nota 10 e são bem transparentes.

**Comment by mjacobus** [comment]
@pablo-sg-pacheco, sua experiência continua sendo boa com o bitwage? Pelo que vi no dia 5/10/2017  tu recebeu apenas 1 centavo a menos por euro, foi isto mesmo?

Tu recebe como PJ ou PF?

**Comment by pablo-sg-pacheco** [comment]
@mjacobus Minha experiência tem sido maravilhosa com o bitwage.
Eu estou agora assinando o plano pago deles. 60 reais fixos por mês. Com isso recebo o dinheiro de forma integral. Nada é descontado. E a taxa de conversão é muito boa. O dinheiro cai direto na minha conta.

Eu sou PJ mas estou recebendo na minha conta de pessoa física ainda. Mas logo logo vou mudar isso. Estou abrindo uma conta digital para empresa no Santander, a chamada Superdigital, onde tenho que pagar 10 reais por mês.

**Comment by Bruno-Furtado** [comment]
@pablo-sg-pacheco, tenho conta PJ e PF no [Banco Inter](https://www.bancointer.com.br). Não pago tarifas em ambas (mensalidade, TED, emissão de boleto, etc). A minha conta PJ é para uma empresa ME, mas recentemente o banco abriu a opção para empresas MEI também. Sou cliente a quase 2 anos e não tenho do que reclamar.

**Comment by nearutranslations** [comment]
@pablo-sg-pacheco 
Obrigado pela sua informaçao.
Tenho algumas dúvidas sobre o Bitwage:
1) Os seus clientes precisam abrir conta no Bitwage ou você fornece uma conta do Bitwage e eles fazem uma transferência normal? 
2) O Dinheiro que você recebe é enviado para a sua conta de Brasil, certo? 
3) Li que a Bitwage é usada para pagamento de salários, pode ser usado simplesmente para fazer transferências?
4) A Bitwage emite nota fiscal (emitida no Brasil) sobre o 1% que é cobrado nas transferências? Se não for assim, o meu contador falou que poderia ter problema.
Obrigado

**Comment by pablo-sg-pacheco** [comment]
;)

1. Eles precisam fazer conta
2. Isso
3. Eu acho que não, mas eu não estou mais usando o Bitwage tem 1 ano, então eles podem ter alterado isso
4. Boa pergunta, não sei dizer

Agora eu estou recebendo direto no meu banco, sem usar a Bitwage.
Estou usando o serviço de câmbio da BS2 que faz a conversão em dólar pra real e manda pra minha conta no banco Inter.

**Comment by lucas-barros** [comment]
@pablo-sg-pacheco quais são as taxas do BS2 pro serviço de cambio?

**Comment by pablo-sg-pacheco** [comment]
Vou te falar que eu não sei exatamente as taxas, mas até agora foi o mais
em conta que eu encontrei

**Comment by nearutranslations** [comment]
Obrigado Pablo,
Esse, BS2 parece bem legal. Vou estudar um poco mais ele para os trabalhos grandes nos quais é melhor ter uma taxa fixa. 
Para os trabalhos pequenos ainda continuo procurando uma alternativa ao PayPal com menor custo em porcentagem, que seja fácil e gratuita para os clientes. Por enquanto minhas alternativas não estão dando certo:
-Transferwise não serve para PJ; 
-Remessa Online e similares usam dados de bancos intermediários e os clientes cometem erros e pagam (pagamos) taxas absurdas;
-Payoneer não tem escritório no Brasil, não emite nota fiscal no Brasil, o que significa que o custo (spread) deles é contabilizado como importação de serviços (problema).
Se alguém tiver alguma outra alternativa, agradeço muito.
Att,

**Comment by lucas-barros** [comment]
@nearutranslations estou pensando em usar o serviço do remessa online, pelo que eu vi é uma taxa fixa de 1.3%. Você já teve, ou conhece alguem que teve, uma experiencia negativa com o serviço deles?

**Comment by gabrielbunselmeyer** [comment]
> Transferwise não serve para PJ;

@nearutranslations Ué, não tava sabendo dessa parte. Tem alguma regra deles contra conta de empresa?

**Comment by lucas-barros** [comment]
@gabrielbunselmeyer  https://transferwise.com/pt/help/14/moedas/2932353/transferencias-para-brl

**Comment by gabrielbunselmeyer** [comment]
@lucas-barros Wow. Pensei que minha pesquisa e entendimento da TransferWise já tava o suficiente. Quer dizer que, no meu caso, estou preso a continuar como PF, mesmo que usando a Borderless Account e recebendo o dinheiro na conta virtual que disponibilizam na Bélgica, e fazendo o processo de me enviar no Brasil eu mesmo.

**Comment by lucas-barros** [comment]
@gabrielbunselmeyer pelo que eu sei, não é possivel transferir para uma conta PJ usando o transferwise, dessa forma você não consegui declarar esse rendimento pela empresa e terá que pagar imposto de renda como PF. Eu não sou contador, então não posso te dizer isso com certeza, isso foi a conclusao que eu cheguei pelas minha pesquisas.

**Comment by nearutranslations** [comment]
> 
> 
> @nearutranslations estou pensando em usar o serviço do remessa online, pelo que eu vi é uma taxa fixa de 1.3%. Você já teve, ou conhece alguem que teve, uma experiencia negativa com o serviço deles?

O principal problema e que tem que enviar ao cliente os dados do banco principal e do intermediário, e os bancos de alguns clientes não permitem adicionar a informação dos 2 bancos. Isso pode gerar problemas.

**Comment by nearutranslations** [comment]
@gabrielbunselmeyer é isso mesmo que o @lucas-barros  falou. No Brasil transferwise só pode enviar de PF a PF, também não pode receber de PJ de outro país.

**Comment by lucas-barros** [comment]
> > @nearutranslations estou pensando em usar o serviço do remessa online, pelo que eu vi é uma taxa fixa de 1.3%. Você já teve, ou conhece alguem que teve, uma experiencia negativa com o serviço deles?
> 
> O principal problema e que tem que enviar ao cliente os dados do banco principal e do intermediário, e os bancos de alguns clientes não permitem adicionar a informação dos 2 bancos. Isso pode gerar problemas.

Ok, entendi. Vou procurar outras alternativas.

**Comment by lucas-barros** [comment]
@pablo-sg-pacheco você já usou o serviço de cambio do banco Inter para receber pagamentos?

**Comment by copercini** [comment]
@lucas-barros o banco Inter usa o mesmo formato do remessa online, com banco intermediário. Acho que isso é meio padrão

**Comment by lucas-barros** [comment]
@copercini hmm entendi. Voce sabe se o BS2 opera de uma forma diferente? Vale apena abrir uma conta nele?

**Comment by copercini** [comment]
@lucas-barros não sei te dizer sobre o BS2 pois me pediram uma pilha de documentos e acabei desistindo por preguiça kkkk

Um que tem IBAN direto (sem banco intermediário) é o Cotação, mas tem a taxinha de 20 dólares por remessa recebida
