### ISSUE TITLE
Banco com isenção de taxa de câmbio

### ISSUE THREAD

**Issue by rafaelweingartner** [DyegoCosta/trabalhando-remoto#55]
Existem bancos que não cobram essa taxa de câmbio mesmo?

Por exemplo, vi na lista que Bradesco não cobraria, mas Bradesco prime cobra? Pra mim me parece que seria o contrario. Assim como o Banco do Brasil que sempre me pareceu taxar tudo (pelo menos para compra de moedas eles possuem taxas). 

P.S. muito interessante o material que tu organizasse aqui 👍 
P.S.2: Eu vi o outro issue sobre esse assunto. Estava tudo muito bacana, mas depois um pseudo italiano fez tudo desandar...

**Comment by renatonascalves** [comment]
Não conheço nenhum banco que não cobre pelo _spread_, taxa de câmbio. Todos cobram, além de outras  taxas.

**Comment by rafaelweingartner** [comment]
Ok, muito obrigado. Vou fechar o issue.

**Comment by fforbeck** [comment]
Banco Inter.
