### ISSUE TITLE
Adicionar Xoom como forma de pagamento digital

### ISSUE THREAD

**Issue by thelinuxlich** [DyegoCosta/trabalhando-remoto#6]
Da última vez que utilizei, tive uma taxa pequena de 5 dólares e nada mais 

https://www.xoom.com/

**Comment by DyegoCosta** [comment]
[Adicionado](https://github.com/DyegoCosta/trabalhando-remoto/commit/9193af81ac387e020aedf2048f3dac3833ba30e1)! Valeu @thelinuxlich
