### ISSUE TITLE
Links do Grokpodcast quebrados

### ISSUE THREAD

**Issue by victor-rocha** [DyegoCosta/trabalhando-remoto#62]
Parece que os donos (ou ex-donos) do Grokpodcast não estão mais pagando o domínio, e com isso os links para os 5 episódios estão quebrados.
A lista de episódios está disponível em alguns sites, mas os aúdios não. 

Removeremos do README ou entraremos em contato com Carlos Brando e o Rafael Rosa Fu para tentar resgatar esses e talvez até outros episódios?

Abraços.

**Comment by lucianosousa** [comment]
@carlosbrando, @rafaelrosafu

**Comment by DyegoCosta** [comment]
@tapajos, @caffo

**Comment by DyegoCosta** [comment]
Se alguém possuir os episódios e puder compartilhar para que possamos adicionar a este repo seria ótimo!

**Comment by tapajos** [comment]
Acho que só o @rafaelrosafu

**Comment by rafaelrosafu** [comment]
Salve,

Estamos com um problema com a empresa que registra domínios, se tudo correr bem vamos resolver tudo até o fim do mês. Minha recomendação é manter os links como estão por enquanto.

**Comment by fabricadecodigo** [comment]
Resolvi no pull request: https://github.com/DyegoCosta/trabalhando-remoto/pull/74
