### ISSUE TITLE
Modelo de Contrato 

### ISSUE THREAD

**Issue by yuriploc** [DyegoCosta/trabalhando-remoto#70]
Olá,

Alguém tem modelo de contrato para compartilhar? O banco está me pedindo um contrato assinado por mim (freelancer; PJ) e meu contratante para que eu possa receber como PJ (MEI).

**Comment by copercini** [comment]
Procura por: Independent contractor agreement template

**Comment by yuriploc** [comment]
Para finalizar a issue, peguei o modelo de `Independent Contractor` no https://www.rocketlawyer.com/.

É um site pago, mas te dão 7 dias de trial, então dá pra fazer tudo direitnho. Eles têm um form com perguntas que ajudam a preencher o contrato, recomendo.
