### ISSUE TITLE
Dúvida sobre o nome no contrato

### ISSUE THREAD

**Issue by fredzica** [DyegoCosta/trabalhando-remoto#77]
Primeiramente muito obrigado por toda a informacão. Tem ajudado muito.

Vou assinar um contrato de trabalho com uma empresa de fora para trabalhar remotamente. E farei o faturamento através de um PJ aqui no Brasil. Nesse contrato precisa ter alguma coisa identificando o PJ que estou abrindo ou apenas meu nome será suficiente? Estou pensando no caso de eu precisar comprovar de onde o dinheiro vem.

Obrigado!

**Comment by copercini** [comment]
Eu tinha feito no meu nome, e depois de abrir empresa tive que mudar o contrato para o nome da empresa (com sufixo -ME) e por o CNPJ, pois o banco Inter só recebe remessas na conta PJ se o contrato estiver com o CNPJ, provavelmente outros bancos também tenham isso.

**Comment by fredzica** [comment]
Muito obrigado.

Vou ter que mudar o contrato quando tiver o CNPJ pronto então.
