### ISSUE TITLE
Declaração de imposto de renda

### ISSUE THREAD

**Issue by AndreNeves97** [DyegoCosta/trabalhando-remoto#81]
Galera, bom dia. Embora tenha algumas outras Issues relacionadas ao assunto, ainda não estou seguro quanto às minhas dúvidas sobre, então resolvi abrir essa para contar com a ajuda da comunidade.

Eu estou começando agora trabalho de freelancer. Não tenho CNPJ, e pelo que vi, não posso ser um desenvolvedor pelo regime MEI, nesse caso eu deveria aderir ao regime Simples Nacional, o que tenho achado inviável atualmente. Outra opção que tenho visto é solicitar emissão de RPA (Recibo de pagamento autônomo)

Comecei pela workana. Minha dúvida é sobre a forma correta de fazer a declaração do imposto de renda sobre os valores recebidos (já estou considerando o caso onde os valores serão suficientes para que seja necessária a declaração de imposto).

Sobre isso, tenho algumas questões:

- O Workana emite algum tipo de recibo que tem validade legal para comprovação da renda e declaração de imposto de renda? Ou é necessário pedir ao meu cliente que emita para mim o RPA do serviço?

- Caso eu trabalhe em algum site como freelancer.com, com prestação de serviços para estrangeiros, como eu faço para declarar os ganhos? A plataforma emite algum recibo que tenha validade legal para comprovação de renda? Ou também é necessário trabalhar com algum tipo de "RPA" ou "Nota fiscal"? (recentemente conheci sobre o "Invoice").

Desde já agradeço

**Comment by herodrigues** [comment]
Se quiser continuar morando no Brasil, emita Darf mensal e pague só o mínimo do INSS (não vai compensar pagar o teto). Aqui: https://github.com/DyegoCosta/trabalhando-remoto#pessoa-f%C3%ADsica

Quando seu faturamento aumentar, não pense duas vezes antes de abrir uma empresa. Caso contrário, você vai entrar em depressão por conta do imposto de PF.
Se você mora nos grandes centros, é até mais tranquilo abrir uma empresa (não é meu caso).

Fora isso, tenho mais duas sugestões radicais:
- Muda para um país mais livre economicamente
- Sonegue

**Comment by AndreNeves97** [comment]
Obrigado @herodrigues, estou olhando essas questões!
