### ISSUE TITLE
paypal

### ISSUE THREAD

**Issue by boaglio** [DyegoCosta/trabalhando-remoto#9]
Acho que é interessante comentar que o Paypal possui um gerador de invoice também.

**Comment by DyegoCosta** [comment]
@boaglio a invoice gerada pelo PayPal tem a intenção de ser paga através do PayPal ou pode ser criada/impressa como uma invoice normal tipo a dos outros serviços de invoice?

**Comment by boaglio** [comment]
Paga pelo PayPal mesmo.

**Comment by DyegoCosta** [comment]
Valeu @boaglio!
