### ISSUE TITLE
Alguém com plano de saúde?

### ISSUE THREAD

**Issue by lbrito1** [DyegoCosta/trabalhando-remoto#96]
Pessoal, como vocês fazem plano de saúde? 

Tenho encontrado dificuldades para fazer um enquanto PF ou PJ. Tenho CNPJ ME. Me parece que o procedimento pra MEI é mais simples, mas pra ME com 1 pessoa, é basicamente impossível.

**Comment by DyegoCosta** [comment]
Eu fiz para duas pessoas com a Amil e meses depois tirei a segunda pessoa, continuou funcionando normalmente e o valor baixou para o de uma pessoa.

**Comment by nobre84** [comment]
Na Unimed Juiz de Fora, só é possível fazer o plano PJ para MEs que tenham no mínimo 6 meses de operação. Então na época migrei o meu antigo plano da empresa que trabalhava CLT para o  individual (eu, esposa e 2 filhas). Após os 6 meses migrei para o corporativo, com a mesma cobertura e mais barato. A empresa não tem sócio ou funcionário.

**Comment by lbrito1** [comment]
@nobre84 Como foi essa migração, eles aceitaram de boa? Tem sido muito difícil achar planos individuais de fato (por CPF), então assumo que no seu caso foi por adesão (intermediado por uma operadora tipo Qualicorp). Eles exigiram contracheque, algo assim?

**Comment by nobre84** [comment]
Aqui em Juiz de Fora foi bem simples. Poderia ser por adesão via SESC da minha esposa ou por categoria profissional autônomo, mas fiz o individual por CPF mesmo, pois precisaria esperar a liberação de alguns documentos e não queria ficar sem cobertura na virada do contrato.
Para 3 pessoas (35, 35, 6) cobertura apartamento era +- 700 reais no adesão, 1000 no individual. Pelo CNPJ para 4 pessoas (35, 35, 6, 0) foi 760, com a mesma cobertura.
Mas cada cidade e seus convênios podem ter suas próprias regras, aqui foi bem simples. Em outros convênios que fiz orçamento também foi de boa.
