### ISSUE TITLE
Diferença entre os CNAE de TI

### ISSUE THREAD

**Issue by aracyla** [DyegoCosta/trabalhando-remoto#97]
#### Fala aew galere, 

Eu to no processo de abrir um cnpj com a contabilizei e, enquanto espero o processor caminhar, ando lendo sobre o assunto.

Eu, acho, que entendi a maior parte das coisas - e o que entendi parcialmente, acredito que acabarei entendo quando precisar botar a mão na massa com as rotinas tributárias/afins.

A única coisa que não entendi é a diferença entre os CNAEs de TI. Seguem algumas dúvidas:

* Na prática eu preciso ter algum rigor quanto a escolha do CNAE? A impressão que eu tenho, é que sempre tem um ou dois que são cabíveis em uma mesma atividade.

###### Eu sinceramente não sei se sou eu que não sei interpretar texto, ou a pessoa que escreveu a descrição/definição desses CNAE não entende absolutamente nada de ti.

**Comment by pocesar** [comment]
você pode atribuir vários, mas vai ter uma atividade principal. normalmente essa é que vai determinar seus anexos (e a faixa de imposto). se for usar o endereço residencial, alguns irão ficar de fora

**Comment by aracyla** [comment]
Obrigado. Se eu posso atribuir vários não vejo problema.

A pergunta foi mais pq eu havia lido e não estava conseguindo caracterizar minha atividade em apenas um deles.

* Por exemplo até agora não sei a diferença entre essas atvidades aqui

6201-5 - Desenvolvimento de programas de computador sob encomenda
6202-3 - Desenvolvimento e licenciamento de programas de computador customizáveis
6203-1 - Desenvolvimento e licenciamento de programas de computador não-customizáveis

###### A descrição também não ajuda muito. De qualquer forma você já "resolveu" meu problema. Vou fechar issue

**Comment by copercini** [comment]
Segundo o IBGE:

`6201-5 - Desenvolvimento de programas de computador sob encomenda`
- o desenvolvimento de sistemas para atender às necessidades do cliente, ou seja, as atividades voltadas para a definição dos módulos, especificações funcionais internas, tipos de relatórios e testes de avaliação do desempenho
- a programação com o uso de ferramentas e de linguagens de programação
- o fornecimento de documentação de programas de computador desenvolvidos sob encomenda
- o desenvolvimento de projetos e modelagem de banco de dados sob encomenda


`6202-3 - Desenvolvimento e licenciamento de programas de computador customizáveis`
- o desenvolvimento de sistemas ou programas de computador (software) que permitem a realização de customizações (adaptações às necessidades específicas de um cliente ou mercado particular)
- o licenciamento ou a outorga de autorização de uso dos programas de computador customizáveis; este licenciamento é freqüentemente obtido através da própria empresa que os desenvolveu ou de seus representantes

`6203-1 - Desenvolvimento e licenciamento de programas de computador não-customizáveis`
- o desenvolvimento de sistemas ou programas de computador que não permitem customizações (adaptações às necessidades específicas de um cliente ou mercado particular). Esses programas são, em geral, adquiridos no comércio, embora possam ser também obtidos diretamente da empresa que os desenvolveu ou através de seus distribuidores e representantes, como, por exemplo:
  - sistemas operacionais
  - aplicativos para empresas e para outras finalidades
  - jogos de computador para todas as plataformas
- o licenciamento ou a outorga de autorização de uso dos programas de computador não-customizáveis
- os distribuidores autorizados de programas de computador não-customizáveis, que são responsáveis pela concessão e regularização de licenças para uso, treinamento, etc.

----
Na prática o imposto é o mesmo, então vc pode escolher o que achar mais bonito
